name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "10 10 * * *"

jobs:
  linux-x86_64:
    name: linux-x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://dawn.googlesource.com/dawn dawn
          mkdir -p dawn/build-debug dawn/build-release dist-debug dist-release
      - name: Install Dependencies
        run: |
          python3 tools/fetch_dawn_dependencies.py
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          wget https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip
          unzip ninja-linux.zip
          sudo cp ninja /usr/bin
          rm ninja-linux.zip
          sudo apt-get install libxrandr-dev libxi-dev libxinerama-dev libxcursor-dev mesa-common-dev libx11-xcb-dev pkg-config
        working-directory: dawn
      - name: Building - Debug
        run: |
          cmake .. -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../dist-debug -DDAWN_ENABLE_INSTALL=ON -DDAWN_BUILD_SAMPLES=OFF -DGLFW_INSTALL=OFF -DDAWN_USE_GLFW=ON -DGLFW_BUILD_WAYLAND=ON -DGLFW_BUILD_X11=ON -DGLFW_LIBRARY_TYPE=STATIC -DTINT_BUILD_TESTS=OFF -DTINT_ENABLE_INSTALL=OFF
          ninja
          ninja install
        working-directory: dawn/build-debug
      - name: Upload - Debug
        uses: actions/upload-artifact@v3
        with:
          path: dist-debug
          name: x86_64-unknown-linux-gnu-debug
      - name: Building - Release
        run: |
          cmake .. -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../dist-release -DDAWN_ENABLE_INSTALL=ON -DDAWN_BUILD_SAMPLES=OFF -DGLFW_INSTALL=OFF -DDAWN_USE_GLFW=ON -DGLFW_BUILD_WAYLAND=ON -DGLFW_BUILD_X11=ON -DGLFW_LIBRARY_TYPE=STATIC -DTINT_BUILD_TESTS=OFF -DTINT_ENABLE_INSTALL=OFF
          ninja
          ninja install
        working-directory: dawn/build-release
      - name: Upload - Release
        uses: actions/upload-artifact@v3
        with:
          path: dist-release
          name: x86_64-unknown-linux-gnu-release

  macos-aarch64:
    name: macos-aarch64
    runs-on: macos-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://dawn.googlesource.com/dawn dawn
          mkdir -p dawn/build-debug dawn/build-release dist-debug dist-release
      - name: Install Dependencies
        run: |
          python3 tools/fetch_dawn_dependencies.py
        working-directory: dawn
      - name: Building - Debug
        run: |
          cmake .. -GXcode -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_INSTALL_PREFIX=../../dist-debug -DDAWN_ENABLE_INSTALL=ON -DDAWN_BUILD_SAMPLES=OFF -DGLFW_INSTALL=OFF -DDAWN_USE_GLFW=ON -DGLFW_LIBRARY_TYPE=STATIC -DTINT_BUILD_TESTS=OFF -DTINT_ENABLE_INSTALL=OFF
          cmake --build . --config Debug
          cmake --install . --config Debug
        working-directory: dawn/build-debug
      - name: Upload - Debug
        uses: actions/upload-artifact@v3
        with:
          path: dist-debug
          name: aarch64-apple-darwin-debug
      - name: Building - Release
        run: |
          cmake .. -GXcode -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_INSTALL_PREFIX=../../dist-release -DDAWN_ENABLE_INSTALL=ON -DDAWN_BUILD_SAMPLES=OFF -DGLFW_INSTALL=OFF -DDAWN_USE_GLFW=ON -DGLFW_LIBRARY_TYPE=STATIC -DTINT_BUILD_TESTS=OFF -DTINT_ENABLE_INSTALL=OFF
          cmake --build . --config Release
          cmake --install . --config Release
        working-directory: dawn/build-release
      - name: Upload - Release
        uses: actions/upload-artifact@v3
        with:
          path: dist-release
          name: aarch64-apple-darwin-release


  macos-x86_64:
    name: macos-x86_64
    runs-on: macos-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://dawn.googlesource.com/dawn dawn
          mkdir -p dawn/build-debug dawn/build-release dist-debug dist-release
      - name: Install Dependencies
        run: |
          python3 tools/fetch_dawn_dependencies.py
        working-directory: dawn
      - name: Building - Debug
        run: |
          cmake .. -GXcode -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_INSTALL_PREFIX=../../dist-debug -DDAWN_ENABLE_INSTALL=ON -DDAWN_BUILD_SAMPLES=OFF -DGLFW_INSTALL=OFF -DDAWN_USE_GLFW=ON -DGLFW_LIBRARY_TYPE=STATIC -DTINT_BUILD_TESTS=OFF -DTINT_ENABLE_INSTALL=OFF
          cmake --build . --config Debug
          cmake --install . --config Debug
        working-directory: dawn/build-debug
      - name: Upload - Debug
        uses: actions/upload-artifact@v3
        with:
          path: dist-debug
          name: x86_64-apple-darwin-debug
      - name: Building - Release
        run: |
          cmake .. -GXcode -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_INSTALL_PREFIX=../../dist-release -DDAWN_ENABLE_INSTALL=ON -DDAWN_BUILD_SAMPLES=OFF -DGLFW_INSTALL=OFF -DDAWN_USE_GLFW=ON -DGLFW_LIBRARY_TYPE=STATIC -DTINT_BUILD_TESTS=OFF -DTINT_ENABLE_INSTALL=OFF
          cmake --build . --config Release
          cmake --install . --config Release
        working-directory: dawn/build-release
      - name: Upload - Release
        uses: actions/upload-artifact@v3
        with:
          path: dist-release
          name: x86_64-apple-darwin-release
