name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "10 10 * * *"

jobs:
  linux-x86_64:
    name: linux-x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://dawn.googlesource.com/dawn dawn
          mkdir -p dawn/build-debug dawn/build-release dist-debug dist-release
      - name: Install Dependencies
        run: |
          python3 tools/fetch_dawn_dependencies.py
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          wget https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip
          unzip ninja-linux.zip
          sudo cp ninja /usr/bin
          rm ninja-linux.zip
          sudo apt-get install libxrandr-dev libxi-dev libxinerama-dev libxcursor-dev mesa-common-dev libx11-xcb-dev pkg-config
        working-directory: dawn
      - name: Building - Debug
        run: |
          cmake .. -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../dist-debug -DDAWN_ENABLE_INSTALL=ON -DDAWN_BUILD_SAMPLES=OFF -DGLFW_INSTALL=OFF -DDAWN_USE_GLFW=ON -DGLFW_BUILD_WAYLAND=ON -DGLFW_BUILD_X11=ON -DGLFW_LIBRARY_TYPE=STATIC -DTINT_BUILD_TESTS=OFF -DTINT_ENABLE_INSTALL=OFF
          ninja
          ninja install
        working-directory: dawn/build-debug
      - name: Building - Release
        run: |
          cmake .. -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../dist-release -DDAWN_ENABLE_INSTALL=ON -DDAWN_BUILD_SAMPLES=OFF -DGLFW_INSTALL=OFF -DDAWN_USE_GLFW=ON -DGLFW_BUILD_WAYLAND=ON -DGLFW_BUILD_X11=ON -DGLFW_LIBRARY_TYPE=STATIC -DTINT_BUILD_TESTS=OFF -DTINT_ENABLE_INSTALL=OFF
          ninja
          ninja install
        working-directory: dawn/build-release
      - name: Create archives
        run: |
          sudo apt install p7zip-full
          mkdir dist
          7z a dist/linux-x86_64-debug.zip dist-debug
          7z a dist/linux-x86_64-release.zip dist-release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: dist

  macos-aarch64:
    name: macos-aarch64
    runs-on: macos-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://dawn.googlesource.com/dawn dawn
          mkdir -p dawn/build-debug dawn/build-release dist-debug dist-release
      - name: Install Dependencies
        run: |
          python3 tools/fetch_dawn_dependencies.py
        working-directory: dawn
      - name: Building - Debug
        run: |
          cmake .. -GXcode -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_INSTALL_PREFIX=../../dist-debug -DDAWN_ENABLE_INSTALL=ON -DDAWN_BUILD_SAMPLES=OFF -DGLFW_INSTALL=OFF -DDAWN_USE_GLFW=ON -DGLFW_LIBRARY_TYPE=STATIC -DTINT_BUILD_TESTS=OFF -DTINT_ENABLE_INSTALL=OFF
          cmake --build . --config Debug
          cmake --install . --config Debug
        working-directory: dawn/build-debug
      - name: Building - Release
        run: |
          cmake .. -GXcode -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_INSTALL_PREFIX=../../dist-release -DDAWN_ENABLE_INSTALL=ON -DDAWN_BUILD_SAMPLES=OFF -DGLFW_INSTALL=OFF -DDAWN_USE_GLFW=ON -DGLFW_LIBRARY_TYPE=STATIC -DTINT_BUILD_TESTS=OFF -DTINT_ENABLE_INSTALL=OFF
          cmake --build . --config Release
          cmake --install . --config Release
        working-directory: dawn/build-release
      - name: Create archives
        run: |
          brew install p7zip
          mkdir dist
          7z a dist/macos-aarch64-debug.zip dist-debug
          7z a dist/macos-aarch64-release.zip dist-release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: dist


  macos-x86_64:
    name: macos-x86_64
    runs-on: macos-latest
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://dawn.googlesource.com/dawn dawn
          mkdir -p dawn/build-debug dawn/build-release dist-debug dist-release
      - name: Install Dependencies
        run: |
          python3 tools/fetch_dawn_dependencies.py
        working-directory: dawn
      - name: Building - Debug
        run: |
          cmake .. -GXcode -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_INSTALL_PREFIX=../../dist-debug -DDAWN_ENABLE_INSTALL=ON -DDAWN_BUILD_SAMPLES=OFF -DGLFW_INSTALL=OFF -DDAWN_USE_GLFW=ON -DGLFW_LIBRARY_TYPE=STATIC -DTINT_BUILD_TESTS=OFF -DTINT_ENABLE_INSTALL=OFF
          cmake --build . --config Debug
          cmake --install . --config Debug
        working-directory: dawn/build-debug
      - name: Building - Release
        run: |
          cmake .. -GXcode -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_INSTALL_PREFIX=../../dist-release -DDAWN_ENABLE_INSTALL=ON -DDAWN_BUILD_SAMPLES=OFF -DGLFW_INSTALL=OFF -DDAWN_USE_GLFW=ON -DGLFW_LIBRARY_TYPE=STATIC -DTINT_BUILD_TESTS=OFF -DTINT_ENABLE_INSTALL=OFF
          cmake --build . --config Release
          cmake --install . --config Release
        working-directory: dawn/build-release
      - name: Create archives
        run: |
          brew install p7zip
          mkdir dist
          7z a dist/macos-x86_64-debug.zip dist-debug
          7z a dist/macos-x86_64-release.zip dist-release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: dist


  publish:
    name: Publish Github release
    needs:
      - linux-x86_64
      - macos-aarch64
      - macos-x86_64
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v4
      - name: Set Version
        run: |
          echo "RELEASE_VERSION=$(date '+%Y%m%d')" >> $GITHUB_ENV
        shell: bash
      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          files: |
            dist/*.zip
          draft: false
          prerelease: false
